name: 07-EnvVariables

on:
    push
env:
    local_var: "local Variable"
    global_var: "Global Variable at Workflow level"

jobs:
    VariableLearning:
        env:
            local_Job_var: "local Job Variable"
            global_var: "Global Variable at Job definition level"
        runs-on: ubuntu-latest
        steps:
            - name: Checking Variable Values
              env:
                local_step_var: "this is local Step Variable"
              run: |
                echo "local_var at workflow leveL: ${{ env.local_var }}"
                echo "local_var at job leveL: ${{ env.local_Job_var }}"
                echo "local_var at step leveL: ${{ env.local_step_var }}"
                echo "global_var defined at Step leveL: ${{ env.global_var }}"