name: 08-Functions

on:
    push

jobs:
    status-check-functions:
        runs-on: ubuntu-latest
        steps:
            - name: cancelled function
              if: ${{ !cancelled() }}
              run: |
                echo "this is cancelled function"
            - name: Always Function
              if: always()
              run: |
                echo "this functions always runs"
            - name: Success Function
              if: success()
              run: echo "this is success function"
            - name: fauilure function
              if: failure()
              run: echo "this is failure function"