name: Setup Node and Python using Actions

on:
    workflow_dispatch

jobs:
    NodeSetup:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '24.x'

            - name: Node Setup Completed
              run: echo " Node setup completed"

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.14.7'
            
            - name: Check Python
              run: |
                python --version
                pip --version

            - name: Python Setup Completed
              run: echo "Python Setup completed"
