name: context Practice

on:
    workflow_dispatch

jobs:
    Contexts:
        runs-on: ubuntu-latest
        steps:
            - name: Printing Context value
              run: echo "${{ github.event_name }}"