name: Event Filters

on:
    push:
        branches-ignore:
            - feature

jobs:
    EventfilterDetails:
        runs-on: ubuntu-latest
        steps:
            - name: print event name
              run: echo "${{ github.event_name }}"
            - name: print Repo name
              run: echo "${{ github.repository }}"
            - name: print Branch name
              run: echo "${{ github.ref_name }}"